route:
  group_by: ['alertname']
  #group_wait: 30s
  #group_interval: 5m
  repeat_interval: 3m
  receiver: 'default'
  routes:
    - match:
        alertname: 'HighCPUUsage'
      receiver: 'cpu-warning'
    - match:
        alertname: 'HighMemoryUsage'
      receiver: 'memory-warning'
    - match:
        alertname: 'InstanceDown'
      receiver: 'instance-down'

receivers:
  - name: 'default'
  - name: 'cpu-warning'
    webhook_configs:
      - url: 'http://192.168.10.25:3000/cpu-alert'
  - name: 'memory-warning'
    webhook_configs:
      - url: 'http://192.168.10.25:3000/memory-alert'
  - name: 'instance-down'
    webhook_configs:
      - url: 'http://192.168.10.25:3000/instance-alert'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']