groups:
  - name: MemoryThreshold
    rules:
      - alert: HighMemoryUsage
        expr: job:memory_usage > 60
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage on {{ $labels.instance }}"
          description: "Memory usage on {{ $labels.instance }} is greater than 60%. Current usage: {{ $value }}%"