global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules.yml
  - mem_rules.yml
  - mem_rules_60.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9300']
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:9200']
