# groups:
#  - name: Count greater than 2
#    rules:
#    - alert: CountGreaterThan2
#      expr: promhttp_metric_handler_requests_total{code="200"} > 2
#      for: 30s
groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'